# This is a basic workflow to help you get started with Actions
name: RELEASE
on:
  push:
     tags:
      - v*

jobs:
 test:
    runs-on: ubuntu-latest
    steps:               
      - name: Set env
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get tag
        run: echo ${{ env.tag }}
           
    #  - name: Get release
     #   run: |
      #     curl \
       #      -H "Accept: application/vnd.github.v3+json" \
        #     https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.tag }}  | jq 
      
      - name: Get api data
        run: |
          sudo apt-get install jq
          branch=$(echo $(curl  -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.tag }} | jq '.target_commitish')) >> $GITHUB_ENV
          release_notes=$(echo $(curl  -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.tag }} | jq '.body')) >> $GITHUB_ENV
        #branch=$(echo ${data} | jq -r '.target_commitish' file.json) >> $GITHUB_ENV
        #release_notes=$(echo ${data} | jq  '.body')  
          
      - name: Get branch
        run: |
          echo "branch=$branch" >> $GITHUB_ENV
          echo $branch
          echo ${{ env.branch }}
          
      - name: Get release notes
        run: |
          echo "release_notes=$release_notes" >> $GITHUB_ENV
          echo $release_notes
          echo ${{ env.release_notes }}
          
      - uses: actions/checkout@v2
        with:
          path: src/github.com/goharbor/harbor
      - name: Get version
        run: |
          set -x
          env
          df -h
          release_version=$(cat ./VERSION)
      
      - name: Build Package
        run: |
          wget https://storage.googleapis.com/harbor-releases/$branch/harbor-online-installer-$tag-build.$release_notes.tgz
          wget https://storage.googleapis.com/harbor-releases/$branch/harbor-online-installer-$tag-build.$release_notes.tgz.asc
          
          wget https://storage.googleapis.com/harbor-releases/$branch/harbor-offline-installer-$tag-build.$release_notes.tgz
          wget https://storage.googleapis.com/harbor-releases/$branch/harbor-offline-installer-$tag-build.$release_notes.tgz.asc
        
        
#       - name: Get release
#        run: |
 #         curl \
  #          -H "Accept: application/vnd.github.v3+json" \
   #         https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.tag }} -s | jq   
        
#       - n
#         me: Get release notes
#         run: curl \
#                 -X POST \
#                 -H "Accept: application/vnd.github.v3+json" \
#                 https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
#                 -d '{"tag_name":"v1.0.0","target_commitish":"main","previous_tag_name":"v0.9.2","configuration_file_path":".github/custom_release_config.yml"}'
#                - name: Set env
 #       run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 #     - name: Get tag
 #       run: |
 #         echo $TAG
  #        echo ${{ env.TAG }}
         
     #    echo "TARGET_COMMITISH=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
       #   echo $TARGET_COMMITISH
       #   echo ${{ env.TARGET_COMMITISH }}
#    echo $BRANCH | python -c "import sys, json; print json.load(sys.stdin)['target_commitish']"
         
         
