# This is a basic workflow to help you get started with Actions
name: RELEASE
on:
  push:
     tags:
      - v*

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get tag
        run: |
          echo $TAG
          echo ${{ env.TAG }}
          
      - name: Get branch
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.TAG }}
          branch=${{ github.ref }}
          echo "BRANCH=${target_commitish}" >> $GITHUB_ENV 
          echo $BRANCH
          echo ${{ env.BRANCH }}




#       - n
#         me: Get release notes
#         run: curl \
#                 -X POST \
#                 -H "Accept: application/vnd.github.v3+json" \
#                 https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
#                 -d '{"tag_name":"v1.0.0","target_commitish":"main","previous_tag_name":"v0.9.2","configuration_file_path":".github/custom_release_config.yml"}'
       
         
         
         
         
