# This is a basic workflow to help you get started with Actions
name: RELEASE
on:
  push:
     tags:
      - v*

jobs:
 test:
    runs-on: ubuntu-latest
    steps:               
      - name: Get tag
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $TAG
          echo ${{ env.TAG }}     
      - name: Get release
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.TAG }} -s | jq
      - name: Get api data
        run: |
          wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x ./jq
          sudo cp jq /usr/bin
          BRANCH=$(curl -k -s http://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.TAG }})
          USER=$(echo ${BRANCH} | jq  '.target_commitish')
          
          RELEASE_NOTES=$(curl -k -s http://api.github.com/repos/ExcelsiorLiu/harbor/releases/tags/${{ env.TAG }})
          USER=$(echo ${RELEASE_NOTES} | jq  '.body')  
          
      - name: Get branch
        run: |
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo ${{ env.BRANCH }}
          
      - name: Get release notes
        run: |
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          echo ${{ env.RELEASE_NOTES }}
          
      - uses: actions/checkout@v2
        with:
          path: src/github.com/goharbor/harbor
      - name: Get version
        if:
          contains(steps.changed-files.outputs.modified, 'VERSION')
        run: |
          set -x
          env
          df -h
          release_version=$(cat ./VERSION)
          package_Version=$release_version-'build.'$RELEASE_NOTES
          
          #if [[ $BRANCH == "main" ]]; then
          #  Harbor_Assets_Version=$package_Version
          #  harbor_target_bucket=$harbor_builds_bucket
          #else
          #  Harbor_Assets_Version=$release_version
          #  harbor_target_bucket=$harbor_releases_bucket/$target_branch
          #fi
          #if [[ $BRANCH == "release-"* ]]; then
          #  Harbor_Build_Base_Tag=$release_version
          #else
          #  Harbor_Build_Base_Tag=dev
          #fi

      
      - name: Build Package
        run: |
          wget https://storage.googleapis.com/harbor-releases/$BRANCH/harbor-online-installer-$TAG-build.$RELEASE_NOTES.tgz
          wget https://storage.googleapis.com/harbor-releases/$BRANCH/harbor-online-installer-$TAG-build.$RELEASE_NOTES.tgz.asc
          
          wget https://storage.googleapis.com/harbor-releases/$BRANCH/harbor-offline-installer-$TAG-build.$RELEASE_NOTES.tgz
          wget https://storage.googleapis.com/harbor-releases/$BRANCH/harbor-offline-installer-$TAG-build.$RELEASE_NOTES.tgz.asc
        
        
        
        
#       - n
#         me: Get release notes
#         run: curl \
#                 -X POST \
#                 -H "Accept: application/vnd.github.v3+json" \
#                 https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
#                 -d '{"tag_name":"v1.0.0","target_commitish":"main","previous_tag_name":"v0.9.2","configuration_file_path":".github/custom_release_config.yml"}'
#                - name: Set env
 #       run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 #     - name: Get tag
 #       run: |
 #         echo $TAG
  #        echo ${{ env.TAG }}
         
     #    echo "TARGET_COMMITISH=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
       #   echo $TARGET_COMMITISH
       #   echo ${{ env.TARGET_COMMITISH }}
#    echo $BRANCH | python -c "import sys, json; print json.load(sys.stdin)['target_commitish']"
         
         
