# This is a basic workflow to help you get started with Actions
name: RELEASE
on:
  push:
     tags:
      - v*
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get api
        run: |
          gh api 
              -H "Accept: application/vnd.github.v3+json" 
              /repos/OWNER/REPO/releases
        env:
          tag: ${{ 'tag_name' }}
          branch: target_commitish
          
      - name: Get version
        run: wget https://raw.githubusercontent.com/goharbor/harbor/main/VERSION

#       - name: Get release notes
#         run: curl \
#                 -X POST \
#                 -H "Accept: application/vnd.github.v3+json" \
#                 https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
#                 -d '{"tag_name":"v1.0.0","target_commitish":"main","previous_tag_name":"v0.9.2","configuration_file_path":".github/custom_release_config.yml"}'
       
         
         
         
         
